# Continuous Delivery: Publish on NPM
name: "CD"

on:
    push:
        branches:
            - main
    workflow_dispatch:
        inputs:
            releaseType:
                description: "Release type"
                required: true
                default: "prerelease"
                type: string

concurrency:
    group: "${{ github.workflow }}-${{ github.ref_name }}"
    cancel-in-progress: true

jobs:
    ci:
        uses: ./.github/workflows/ci.yml

    publish-release-or-snapshot:
        if: ${{ inputs.releaseType == '' }}
        needs: ci
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: write
        steps:
            - name: "Checkout repository"
              uses: actions/checkout@v4

            - name: "Setup dependencies"
              uses: ./.github/actions/setup
              with:
                  install_node: true

            - name: "Create version"
              id: version
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  set -x # verbose
                  message=$(git show -s --format=%s)
                  version=$(echo $message | egrep -o '[0-9]+\.[0-9]+\.[0-9]+' || true)

                  if [[ "$message" == 'Release v'* ]] && [ -n "$version" ]; then
                      # Release version

                      # Create tag
                      tag="v${version}"
                      echo "tag=$tag" >> $GITHUB_OUTPUT
                      git tag "$tag"

                      # Push tag
                      git push origin "$tag"
                  else 
                      # Snapshot version

                      name=$(npm pkg get name | sed 's/"//g')
                      previousSnapshotVersion=$(npm show ${name}@snapshot version)
                      
                      # Get the latest version between release and snapshot as the base for the next snapshot
                      previousVersion=$(cat <(npm show ${name}@latest version) <(echo ${previousSnapshotVersion}) | sort -V | tail -n1)
                      
                      # Set base version and create a new snapshot version from it
                      npm pkg set version=${previousVersion}
                      npm version prerelease --preid snapshot --git-tag-version false
                      echo "name=${name}" >> $GITHUB_OUTPUT
                      echo "previousVersion=${previousSnapshotVersion}" >> $GITHUB_OUTPUT

                      echo "publishTag='--tag snapshot'" >> $GITHUB_OUTPUT
                  fi

            - name: "Publish"
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npm publish --provenance --access public ${{ steps.version.outputs.publishTag }}

            - name: "Deprecate previous snapshot"
              if: ${{ steps.version.outputs.previousVersion != '' }}
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npm deprecate ${{ steps.version.outputs.name }}@${{ steps.version.outputs.previousVersion }} "snapshot"

    prepare-release:
        if: ${{ inputs.releaseType != '' && github.ref_name == 'main'  }}
        needs: ci
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: write
        steps:
            - name: "Checkout repository"
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: "Setup dependencies"
              uses: ./.github/actions/setup
              with:
                  install_node: true

            - name: "Bump version"
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  set -x
                  git config --global user.name "github-actions"
                  git config --global user.email "github-actions@users.noreply.github.com"

                  # Version & commit
                  npm version ${{ inputs.releaseType }} --m "Release v%s" ${{ inputs.releaseType == 'prerelease' && '--preid rc' || '' }}

                  title=$(git log -1 --pretty=%B)                
                  branch=$(echo ${title} | tr ' ' '_' | tr '[:upper:]' '[:lower:]')
                  git checkout -b ${branch}

            - name: "Publish"
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npm publish --provenance --access public ${{ inputs.releaseType == 'prerelease' && '--tag prerelease' || '' }}

            - name: "Create pull request"
              uses: actions/github-script@v6
              with:
                  github-token: "${{ secrets.GITHUB_TOKEN }}"
                  script: |
                      github.rest.pulls.create({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          base: 'master',
                          head: '${{ steps.version.outputs.branch }}',
                          title: '${{ steps.version.outputs.title }}',
                          body: '${{ steps.version.outputs.title }}'
                              + 'Review, test and merge to publish to NPM.\n\n'
                              + 'Triggered by @${{ github.actor }}',
                          draft: false,
                      });
