# Continuous Delivery: Publish on NPM
name: "CD"

on:
    push:
        branches:
            - main
    workflow_dispatch:
        inputs:
            releaseType:
                description: "Release type"
                required: true
                default: "prerelease"
                type: string

concurrency:
    group: "${{ github.workflow }}-${{ github.ref_name }}"
    cancel-in-progress: true

jobs:
    ci:
        uses: ./.github/workflows/ci.yml

    publish-snapshot:
        if: ${{ inputs.releaseType == '' }}
        needs: ci
        runs-on: ubuntu-latest
        permissions:
            id-token: write
        steps:
            - name: "Checkout repository"
              uses: actions/checkout@v4

            - name: "Setup dependencies"
              uses: ./.github/actions/setup
              with:
                  install_node: true

            - name: "Create version"
              id: version
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  set -x # verbose
                  name=$(npm pkg get name | sed 's/"//g')
                  previousReleaseVersion=$(npm show ${name}@latest version)
                  previousSnapshotVersion=$(npm show ${name}@snapshot version)

                  # Get the latest version between release and snapshot as the base for the next snapshot
                  previousVersion=$(echo "${previousReleaseVersion}\n${previousSnapshotVersion}" | sort -V | tail -n1)

                  # Set base version and create a new snapshot version from it
                  npm pkg set version=$previousVersion
                  npm version prerelease --preid snapshot --git-tag-version false
                  echo "name=$name" >> $GITHUB_OUTPUT
                  echo "previousVersion=$previousVersion" >> $GITHUB_OUTPUT

            - name: "Publish"
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npm publish --provenance --access public --tag snapshot

            - name: "Deprecate previous snapshot"
              if: ${{ steps.version.outputs.previousVersion != '' }}
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npm deprecate ${{ steps.version.outputs.name }}@${{ steps.version.outputs.previousVersion }} "snapshot"

    publish-release:
        if: ${{ inputs.releaseType != '' && github.ref_name == 'main'  }}
        needs: ci
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: write
        steps:
            - name: "Checkout repository"
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: "Setup dependencies"
              uses: ./.github/actions/setup
              with:
                  install_node: true

            - name: "Bump version"
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  set -x
                  git config --global user.name "github-actions"
                  git config --global user.email "github-actions@users.noreply.github.com"

                  npm version ${{ inputs.releaseType }} --m "Release v%s" ${{ inputs.releaseType == 'prerelease' && '--preid rc' || '' }}

                  git push
                  git push --tags

            - name: "Publish"
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npm publish --provenance --access public ${{ inputs.releaseType == 'prerelease' && '--tag prerelease' || '' }}
