name: "Dependabot: Update bun.lock"

on:
    pull_request:
        paths:
            - package.json

permissions:
    contents: write

jobs:
    update-bun-lock:
        name: "Update bun.lock"
        if: github.actor == 'dependabot[bot]'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
              with:
                  fetch-depth: 0
                  ref: ${{ github.event.pull_request.head.ref }}

            - uses: ./.github/actions/setup
              with:
                  frozen_lockfile: false

            - run: |
                  bun install
                  git add bun.lock
                  git config --global user.name 'dependabot[bot]'
                  git config --global user.email 'dependabot[bot]@users.noreply.github.com'
                  git commit --amend --no-edit 
                  git push --force
